
insert into
	TB_T_EXPORT_ORDER_ATTACHMENT 
	values (
 @NOMOR
,@Param_DATAID                                
,@Param_VERSION                               
,@Param_REVISIONNO                            
,@Param_IMPORTERDCD                           
,@Param_EXPORTERCD                            
,@Param_ODRTYPE                               
,@Param_PCMN                                  
,@Param_CFC                                   
,@Param_REEXPCD                               
,@Param_AICO_CEPT                             
,@Param_PXPLAG                                
,@Param_IMPORTERNAME                          
,@Param_EXPORTERNAME                          
,@Param_SSNO                                  
,@Param_LINECD                                
,@Param_PARTNO                                
,@Param_Lot_Code                              
,@Param_Exterior_Color                        
,@Param_Interior_Color                        
,@Param_Control_Mode_Code                     
,@Param_Display_Mode_Code                     
,@Param_ODRLOT                                
,@Param_MONTH_ORDER_VOLUME_Nmonth             
,@Param_MONTH_ORDER_VOLUME_Nmonth_PLUS_1      
,@Param_MONTH_ORDER_VOLUME_Nmonth_PLUS_2      
,@Param_MONTH_ORDER_VOLUME_Nmonth_PLUS_3      
,@Param_DAILY_VOLUME_1N                       
,@Param_DAILY_VOLUME_2N                       
,@Param_DAILY_VOLUME_3N                       
,@Param_DAILY_VOLUME_4N                       
,@Param_DAILY_VOLUME_5N                       
,@Param_DAILY_VOLUME_6N                       
,@Param_DAILY_VOLUME_7N                       
,@Param_DAILY_VOLUME_8N                       
,@Param_DAILY_VOLUME_9N                       
,@Param_DAILY_VOLUME_10N                      
,@Param_DAILY_VOLUME_11N                      
,@Param_DAILY_VOLUME_12N                      
,@Param_DAILY_VOLUME_13N                      
,@Param_DAILY_VOLUME_14N                      
,@Param_DAILY_VOLUME_15N                      
,@Param_DAILY_VOLUME_16N                      
,@Param_DAILY_VOLUME_17N                      
,@Param_DAILY_VOLUME_18N                      
,@Param_DAILY_VOLUME_19N                      
,@Param_DAILY_VOLUME_20N                      
,@Param_DAILY_VOLUME_21N                      
,@Param_DAILY_VOLUME_22N                      
,@Param_DAILY_VOLUME_23N                      
,@Param_DAILY_VOLUME_24N                      
,@Param_DAILY_VOLUME_25N                      
,@Param_DAILY_VOLUME_26N                      
,@Param_DAILY_VOLUME_27N                      
,@Param_DAILY_VOLUME_28N                      
,@Param_DAILY_VOLUME_29N                      
,@Param_DAILY_VOLUME_30N                      
,@Param_DAILY_VOLUME_31N                      
,@Param_DAILY_VOLUME_1N_PLUS_1                
,@Param_DAILY_VOLUME_2N_PLUS_1                
,@Param_DAILY_VOLUME_3N_PLUS_1                
,@Param_DAILY_VOLUME_4N_PLUS_1                
,@Param_DAILY_VOLUME_5N_PLUS_1                
,@Param_DAILY_VOLUME_6N_PLUS_1                
,@Param_DAILY_VOLUME_7N_PLUS_1                
,@Param_DAILY_VOLUME_8N_PLUS_1                
,@Param_DAILY_VOLUME_9N_PLUS_1                
,@Param_DAILY_VOLUME_10N_PLUS_1               
,@Param_DAILY_VOLUME_11N_PLUS_1               
,@Param_DAILY_VOLUME_12N_PLUS_1               
,@Param_DAILY_VOLUME_13N_PLUS_1               
,@Param_DAILY_VOLUME_14N_PLUS_1               
,@Param_DAILY_VOLUME_15N_PLUS_1               
,@Param_DAILY_VOLUME_16N_PLUS_1               
,@Param_DAILY_VOLUME_17N_PLUS_1               
,@Param_DAILY_VOLUME_18N_PLUS_1               
,@Param_DAILY_VOLUME_19N_PLUS_1               
,@Param_DAILY_VOLUME_20N_PLUS_1               
,@Param_DAILY_VOLUME_21N_PLUS_1               
,@Param_DAILY_VOLUME_22N_PLUS_1               
,@Param_DAILY_VOLUME_23N_PLUS_1               
,@Param_DAILY_VOLUME_24N_PLUS_1               
,@Param_DAILY_VOLUME_25N_PLUS_1               
,@Param_DAILY_VOLUME_26N_PLUS_1               
,@Param_DAILY_VOLUME_27N_PLUS_1               
,@Param_DAILY_VOLUME_28N_PLUS_1               
,@Param_DAILY_VOLUME_29N_PLUS_1               
,@Param_DAILY_VOLUME_30N_PLUS_1               
,@Param_DAILY_VOLUME_31N_PLUS_1               
,@Param_Transportation_Code                   
,@Param_Order_Date                            
,@Param_Series                                
,@Param_Dummy                                 
,@Param_Termination_Code   
,NULL
,NULL 
,null                  
)