exec		@RetVal					= [sp_DestinationMasterSettingsScreen_InsertUpdate]
			@@v_companyCode			= @companyCode,
			@@v_seqNo				= @seqNo,
            @@v_destinationCode		= @destinationCode,
            @@v_destinationName		= @destinationName,
            @@v_exportCode			= @exportCode,
			@@v_leadTime			= @leadTime,
			@@v_eKanban				= @eKanban,
			@@v_tcFrom				= @tcFrom,
			@@v_tcTo				= @tcTo,
			@@v_screenMode			= @screenMode,
			@@v_userId				= @UserId     ,
			@@v_ErrMesg				= @ErrMesg   output 
