DECLARE @@NumberOfDays INT,
		@@QuerySelect  NVARCHAR(MAX) = '',
		@@Params       NVARCHAR(MAX)

SET    @@Params = '@@comcd varchar(4), @@proccd VARCHAR(1), @@yymn VARCHAR(8)'
SELECT @@NumberOfDays = DAY(DATEADD(DD,-1,DATEADD(MM,DATEDIFF(MM,-1, @yearmonth + '01'),0)))

SET @@QuerySelect = '
	SELECT *
	FROM(
		SELECT DYALOCRATIO, VALUE
		FROM(
			SELECT
				DAY_ALOC_RATIO_01,
				DAY_ALOC_RATIO_02,
				DAY_ALOC_RATIO_03,
				DAY_ALOC_RATIO_04,
				DAY_ALOC_RATIO_05,
				DAY_ALOC_RATIO_06,
				DAY_ALOC_RATIO_07,
				DAY_ALOC_RATIO_08,
				DAY_ALOC_RATIO_09,
				DAY_ALOC_RATIO_10,
				DAY_ALOC_RATIO_11,
				DAY_ALOC_RATIO_12,
				DAY_ALOC_RATIO_13,
				DAY_ALOC_RATIO_14,
				DAY_ALOC_RATIO_15,
				DAY_ALOC_RATIO_16,
				DAY_ALOC_RATIO_17,
				DAY_ALOC_RATIO_18,
				DAY_ALOC_RATIO_19,
				DAY_ALOC_RATIO_20,
				DAY_ALOC_RATIO_21,
				DAY_ALOC_RATIO_22,
				DAY_ALOC_RATIO_23,
				DAY_ALOC_RATIO_24,
				DAY_ALOC_RATIO_25,
				DAY_ALOC_RATIO_26,
				DAY_ALOC_RATIO_27,
				DAY_ALOC_RATIO_28,
				DAY_ALOC_RATIO_29,
				DAY_ALOC_RATIO_30,
				DAY_ALOC_RATIO_31
			FROM  TB_M_PROD_COEF
			WHERE 
				COMPANY_CD = @@comcd AND
				PROCESS_CD = @@proccd AND
				YYMM = @@yymn
		) SRC
		UNPIVOT(
			VALUE
			FOR DYALOCRATIO IN (
				DAY_ALOC_RATIO_01,
				DAY_ALOC_RATIO_02,
				DAY_ALOC_RATIO_03,
				DAY_ALOC_RATIO_04,
				DAY_ALOC_RATIO_05,
				DAY_ALOC_RATIO_06,
				DAY_ALOC_RATIO_07,
				DAY_ALOC_RATIO_08,
				DAY_ALOC_RATIO_09,
				DAY_ALOC_RATIO_10,
				DAY_ALOC_RATIO_11,
				DAY_ALOC_RATIO_12,
				DAY_ALOC_RATIO_13,
				DAY_ALOC_RATIO_14,
				DAY_ALOC_RATIO_15,
				DAY_ALOC_RATIO_16,
				DAY_ALOC_RATIO_17,
				DAY_ALOC_RATIO_18,
				DAY_ALOC_RATIO_19,
				DAY_ALOC_RATIO_20,
				DAY_ALOC_RATIO_21,
				DAY_ALOC_RATIO_22,
				DAY_ALOC_RATIO_23,
				DAY_ALOC_RATIO_24,
				DAY_ALOC_RATIO_25,
				DAY_ALOC_RATIO_26,
				DAY_ALOC_RATIO_27,
				DAY_ALOC_RATIO_28,
				DAY_ALOC_RATIO_29,
				DAY_ALOC_RATIO_30,
				DAY_ALOC_RATIO_31
			)
		) PVT
	) [SOURCE]
	WHERE DYALOCRATIO BETWEEN ''DAY_ALOC_RATIO_01'' AND ''DYALOCRATIO'+ CAST(@@NumberOfDays AS VARCHAR) +'''
'; 
EXECUTE sp_executesql @@QuerySelect, @@Params, @@comcd = @company_cd, @@proccd = @process_cd, @@yymn = @yearmonth