select * from (
select ROW_NUMBER() over(order by YYMM asc ) r,
	   COMPANY_CD,
	   LINE_CD,
	   PROCESS_CD,
	   YYMM,
	   CONVERT(DECIMAL(10,2),WORK_DAY_SYSTEM) as WORK_DAY_SYSTEM,
	   CONVERT(DECIMAL(10,2),WORK_DAY_HAND) as WORK_DAY_HAND,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_01) as DAY_ALOC_RATIO_01,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_02) as DAY_ALOC_RATIO_02,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_03) as DAY_ALOC_RATIO_03,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_04) as DAY_ALOC_RATIO_04,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_05) as DAY_ALOC_RATIO_05,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_06) as DAY_ALOC_RATIO_06,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_07) as DAY_ALOC_RATIO_07,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_08) as DAY_ALOC_RATIO_08,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_09) as DAY_ALOC_RATIO_09,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_10) as DAY_ALOC_RATIO_10,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_11) as DAY_ALOC_RATIO_11,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_12) as DAY_ALOC_RATIO_12,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_13) as DAY_ALOC_RATIO_13,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_14) as DAY_ALOC_RATIO_14,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_15) as DAY_ALOC_RATIO_15,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_16) as DAY_ALOC_RATIO_16,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_17) as DAY_ALOC_RATIO_17,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_18) as DAY_ALOC_RATIO_18,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_19) as DAY_ALOC_RATIO_19,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_20) as DAY_ALOC_RATIO_20,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_21) as DAY_ALOC_RATIO_21,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_22) as DAY_ALOC_RATIO_22,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_23) as DAY_ALOC_RATIO_23,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_24) as DAY_ALOC_RATIO_24,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_25) as DAY_ALOC_RATIO_25,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_26) as DAY_ALOC_RATIO_26,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_27) as DAY_ALOC_RATIO_27,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_28) as DAY_ALOC_RATIO_28,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_29) as DAY_ALOC_RATIO_29,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_30) as DAY_ALOC_RATIO_30,
	   CONVERT(DECIMAL(10,2),DAY_ALOC_RATIO_31) as DAY_ALOC_RATIO_31

from TB_M_PROD_COEF
where 1=1
	  and ((@company_cd is null OR @company_cd = '') OR (COMPANY_CD = @company_cd ))
	  and ((@process_cd is null OR @process_cd = '') OR (PROCESS_CD = @process_cd ))
	  and ((@yearmonth is null OR @yearmonth = '') OR (YYMM = @yearmonth ))
)
tb
where 1 = 1 and tb.r between @RowStart and @RowEnd