

SELECT 
	ROW_NUMBER() OVER (ORDER BY CREATED_DT desc) as r, 
		LINE_CD,
		LINE_NAME,
		PROCESS_CD,
		COMPANY_CD
	 
FROM TB_M_LINE
	WHERE 1 =1

	  AND ((@PROCESS_CD is null OR @PROCESS_CD= '') OR (PROCESS_CD = @PROCESS_CD))
