DECLARE @@tc_From VARCHAR(100),
		@@tc_To VARCHAR(100)

SET @@tc_From = CAST(@v_tcFrom AS DATE)
SET @@tc_To   = CAST(@v_tcTo AS DATE)

SELECT DISTINCT 1
FROM(
	SELECT A.PART_NO, A.LINE_CD, A.CFC, A.STATUS_CD, B.COMPANY_CD FROM TB_M_STOCK_LEVEL A
	JOIN TB_M_UNIT_PROD B ON 
		A.PART_NO = B.PART_NO AND A.LINE_CD = B.LINE_CD AND A.CFC = B.CFC AND A.STATUS_CD = B.STATUS_CD AND A.COMPANY_CD = B.COMPANY_CD
	WHERE @@tc_From <= A.TC_TO AND @@tc_To >= A.TC_FROM
)X
WHERE X.PART_NO = @part_no AND X.LINE_CD = @line_cd AND X.CFC = @cfc AND X.STATUS_CD = @status_cd