exec @RetVal = dbo.sp_StockLevelMasterSettingsScreen_Insert
	@@COMPANY_CD = @companyCode,
	@@LINE_CD = @lineCd,
	@@CFC =@cfc,
	@@PART_NO = @partNo,
	@@STATUS_CD = @statusCd,
	@@EXPORT_CD = @exportCd, 
	@@MIN_STOCK = @minStock,
	@@MAX_STOCK = @maxStock,
	@@TC_FROM = @tcFrom,
	@@TC_TO = @tcTo,
	@@userId = @userId,
	@@ErrMesg = @ErrMesg output