SELECT * FROM (
SELECT  DISTINCT ROW_NUMBER() over(order by A.COMPANY_CD asc ) r,
		A.STATUS_CD			[STATUS_CD],
		B.DEST_NAME			[DEST_NAME],
		B.DEST_CD			[DEST_CODE],
		A.ORD_TYPE			[ORD_TYPE],
		C.REVISION			[REVISION],
		C.VERSION			[VERSION],
		A.CFC				[CFC],
		A.TOOL_CD			[TOOL_CD],
		replace(A.PACK_MONTH,substring(A.PACK_MONTH,1,4),substring(A.PACK_MONTH,1,4)+'/')  [PACK_MONTH],
		CONVERT(VARCHAR, CAST(SUBSTRING(A.RECEIVE_TIME, 1, 8) AS DATE), 111) [RECEIVE_DATE],
		SUBSTRING(RECEIVE_TIME, 9, 2)+':'+SUBSTRING(RECEIVE_TIME, 11, 2) [RECEIVE_TIME],
		A.RECEIVE_STAT		[RECEIVE_STAT],
		A.CHECK_STAT		[CHECK_STAT],
		A.DIFF_LIST_STAT	[DIFF_LIST_STAT],
		A.DAY_BY_DAY_STAT	[DAY_BY_DAY_STAT],
		A.K_PACK_CREATE_STAT [K_PACK_CREATE_STAT],
		A.M_PACK_CREATE_STAT [M_PACK_CREATE_STAT],	
		A.CREATED_BY		[CREATED_BY],
		CONVERT(VARCHAR, CAST(SUBSTRING(A.LAST_UPDATE, 1, 8) AS DATE), 111) [LAST_UPDATE_DATE],
		SUBSTRING(LAST_UPDATE, 9, 2)+':'+SUBSTRING(LAST_UPDATE, 11, 2) [LAST_UPDATE_TIME]
FROM TB_R_ORDER_CONTROL A
INNER JOIN TB_M_DESTINATION B ON A.IMPORTER_CD = B.DEST_CD AND B.COMPANY_CD = A.COMPANY_CD
INNER JOIN TB_R_ORDER_SPEC C ON A.RECEIVE_NO = C.RECEIVE_NO AND A.COMPANY_CD = C.COMPANY_CD

where 1=1
		and  ((@STATUS_CD is null OR @STATUS_CD = '') OR (A.STATUS_CD like '%' +@STATUS_CD+'%' ))
		and  ((@IMPORTER_CD is null OR @IMPORTER_CD = '') OR (A.IMPORTER_CD like '%' +@IMPORTER_CD+'%' ))
		and  ((@EXPORTER_CD is null OR @EXPORTER_CD = '') OR (A.EXPORTER_CD like '%' +@EXPORTER_CD+'%' ))
		and  ((@ORD_TYPE is null OR @ORD_TYPE = '') OR (A.ORD_TYPE like '%' +@ORD_TYPE+'%' ))
		and  ((@PACK_MONTH is null OR @PACK_MONTH = '') OR (A.PACK_MONTH like '%' +@PACK_MONTH+'%' ))
		and  ((@CFC is null OR @CFC = '') OR (A.CFC like '%' +@CFC+'%' ))

)tb where 1 = 1  and tb.r between @RowStart and @RowEnd