ALTER PROCEDURE [dbo].[SP_IS_LOCK_FUNCTION]
	@FUNCTION_ID VARCHAR(MAX),
	@FUNCTION_LOCKED BIT OUTPUT,
	@RUN_PROCESS_ID BIGINT OUTPUT
AS
BEGIN
	SET NOCOUNT ON;


	IF EXISTS(
		SELECT * FROM TB_T_LOCK
		WHERE FUNCTION_ID IN
		(
			SELECT DISTINCT TB.FUNCTION_ID
			FROM
			(
				SELECT [FUNCTION_RELATED] FUNCTION_ID 
				FROM dbo.[TB_M_FUNCTION_DEPENDENCY]
				WHERE [FUNCTION_MAIN] = @FUNCTION_ID
			) TB
		)
	)
	BEGIN
		SET @FUNCTION_LOCKED = 1;

		SELECT TOP 1 @RUN_PROCESS_ID = PROCESS_ID FROM TB_T_LOCK
		WHERE FUNCTION_ID IN
		(
			SELECT DISTINCT TB.FUNCTION_ID
			FROM
			(
				SELECT [FUNCTION_RELATED] FUNCTION_ID 
				FROM dbo.[TB_M_FUNCTION_DEPENDENCY]
				WHERE [FUNCTION_MAIN] = @FUNCTION_ID
			) TB
		)
	END
	ELSE
	BEGIN
		SET @FUNCTION_LOCKED = 0;
		SET @RUN_PROCESS_ID = 0;
	END
END