
CREATE PROCEDURE [dbo].[SP_LOG_WRITE_FINISH] 
	-- Add the parameters for the stored procedure here
	@PROCESS_ID bigint, 
	@USER_ID VARCHAR(20),
	@PROCESS_NAME VARCHAR(MAX),
	@PROCESS_STS VARCHAR(MAX),
	@NR_ERR INT OUTPUT

AS

DECLARE @END_DT DATETIME
DECLARE @L_MSG_ID VARCHAR(12)
DECLARE @L_MSG_TEXT VARCHAR(500)
DECLARE @MSG VARCHAR(MAX)
DECLARE @MSG_TYPE VARCHAR(3)

SET @END_DT = GETDATE()
SET @NR_ERR = 0

BEGIN
	IF @PROCESS_STS = '0'--sukses
	BEGIN
		SET @L_MSG_ID = 'MCSTSTD039I'
	END
	ELSE --with error sukses
	BEGIN
		SET @L_MSG_ID = 'MCSTSTD040I'
	END
	
	-- get Message text
	EXEC SP_MESSAGE_GET @L_MSG_ID
		,@MSG OUTPUT
		,@MSG_TYPE OUTPUT
		,@NR_ERR OUTPUT
		,@PROCESS_NAME
		,NULL
		,NULL
		,NULL
		,NULL

	 SET @L_MSG_TEXT =  @MSG-- @L_MSG_ID + ' : ' +@MSG

	EXEC sp_LOG_WRITE_DETAIL @PROCESS_ID
		,@USER_ID
		,'End Log'
		,@L_MSG_ID
		,@L_MSG_TEXT
		,@NR_ERR OUTPUT

	UPDATE T 
		SET T.END_DT = @END_DT,
			T.PROCESS_STS = ISNULL(@PROCESS_STS,'1')
	FROM TB_R_LOG_H T
	WHERE T.PROCESS_ID = @PROCESS_ID

	IF @@ERROR <> 0
	BEGIN
		SET @NR_ERR = 1
		RETURN
	END
END