
CREATE PROCEDURE [dbo].[SP_LOG_WRITE_HEADER] 
	-- Add the parameters for the stored procedure here
	@PROCESS_ID bigint OUTPUT, 
	@FUNCTION_ID VARCHAR(MAX),
	@MODULE_ID VARCHAR(MAX),
	@PROCESS_STS VARCHAR(MAX),
	@USER_ID VARCHAR(MAX),
	@READ_FLAG VARCHAR(MAX),
	@REMARK VARCHAR(50)

AS

DECLARE @START_DT DATETIME
DECLARE @END_DT DATETIME--, 

SET @START_DT = GETDATE()
SET @END_DT = GETDATE()

INSERT TB_R_LOG_H(
		FUNCTION_ID
		,MODULE_ID
		,START_DT
		,END_DT
		,PROCESS_STS
		,USER_ID
		,READ_FLAG
		,REMARK
		)
		VALUES
		(
		@FUNCTION_ID
		,@MODULE_ID
		,@START_DT
		,@END_DT
		,@PROCESS_STS
		,@USER_ID
		,@READ_FLAG
		,@REMARK
		)
SET @PROCESS_ID = @@IDENTITY
