
CREATE PROCEDURE [dbo].[SP_LOG_WRITE_DETAIL] 
	-- Add the parameters for the stored procedure here
	 @PROCESS_ID bigint 
	,@USER_ID VARCHAR(20)
	,@ERR_LOC VARCHAR(100)
	,@MSG_ID VARCHAR(15)
	,@MSG_TEXT VARCHAR(MAX)
	,@NR_ERR INT OUTPUT

	
AS
DECLARE @SEQ_NO INT
	   ,@MSG_TYPE VARCHAR(1)
	   ,@ERR_DT DATETIME

SET @ERR_DT = GETDATE();
SET @NR_ERR = 0
SET @SEQ_NO = isnull((
			SELECT max(SEQ_NO)
			FROM TB_R_LOG_D WITH (NOLOCK)
			WHERE PROCESS_ID = @PROCESS_ID
			), 0) + 1		
IF EXISTS (
		SELECT PROCESS_ID
		FROM TB_R_LOG_H WITH (NOLOCK)
		WHERE PROCESS_ID = @PROCESS_ID
		)

BEGIN
	SET @MSG_TYPE = RIGHT(@MSG_ID, 1);
	BEGIN TRANSACTION

	INSERT TB_R_LOG_D (
		 PROCESS_ID
		,USER_ID
		,SEQ_NO
		,ERR_DT
		,LOC
		,MSG_ID
		,MSG_TYPE
		,MSG_TEXT
		)
	VALUES (
		@PROCESS_ID
		,@USER_ID
		,@SEQ_NO
		,@ERR_DT
		,@ERR_LOC
		,@MSG_ID
		,@MSG_TYPE
		,@MSG_TEXT
		);

		IF @@ERROR <> 0
	BEGIN
		SET @NR_ERR = 1

		ROLLBACK
	END
	ELSE
		COMMIT
END
ELSE
BEGIN
	SET @NR_ERR = 0 --if no log header just ignore
END