
CREATE PROCEDURE [dbo].[SP_MESSAGE_GET]
	-- Add the parameters for the stored procedure here
	@MSG_ID VARCHAR(15),
	@MSG_TXT VARCHAR(MAX) OUTPUT,
	@MSG_TYPE VARCHAR OUTPUT,
	@NR_ERR	INT OUTPUT,
	@PARAM1 VARCHAR(MAX) = NULL,
	@PARAM2 VARCHAR(MAX) = NULL,
	@PARAM3 VARCHAR(MAX) = NULL,
	@PARAM4 VARCHAR(MAX) = NULL,
	@PARAM5 VARCHAR(MAX) = NULL
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
    SET @NR_ERR = 0;
	SET @MSG_TYPE = RIGHT(@MSG_ID, 1);
	SET @MSG_TXT = (SELECT MSG_ID+' : '+MSG_DESC FROM TB_M_MESSAGE WHERE MSG_ID = @MSG_ID)

	IF (@MSG_TXT IS NULL)
	BEGIN
		SET @NR_ERR = 1;
	END

	IF (ISNULL(@PARAM1,'') <> '')
	BEGIN
		SET @MSG_TXT = REPLACE(@MSG_TXT, '{0}', @PARAM1)
	END

	IF (ISNULL(@PARAM2,'') <> '')
	BEGIN
		SET @MSG_TXT = REPLACE(@MSG_TXT, '{1}', @PARAM2)
	END

	IF (ISNULL(@PARAM3,'') <> '')
	BEGIN
		SET @MSG_TXT = REPLACE(@MSG_TXT, '{2}', @PARAM3)
	END

	IF (ISNULL(@PARAM4,'') <> '')
	BEGIN
		SET @MSG_TXT = REPLACE(@MSG_TXT, '{3}', @PARAM4)
	END

	IF (ISNULL(@PARAM5,'') <> '')
	BEGIN
		SET @MSG_TXT = REPLACE(@MSG_TXT, '{4}', @PARAM5)
	END

END