CREATE PROCEDURE [dbo].[SP_UNLOCK_FUNCTION]
	@PROCESS_ID INT,
	@FUNCTION_ID VARCHAR(MAX)
AS
BEGIN
	SET NOCOUNT ON;

	DELETE TB_T_LOCK
	WHERE FUNCTION_ID IN
	(
		SELECT DISTINCT TB.FUNCTION_ID
		FROM
		(
			SELECT @FUNCTION_ID FUNCTION_ID
		) TB
	) AND PROCESS_ID = @PROCESS_ID;
END