
DECLARE @@lastSeq INT;

SELECT @@lastSeq = MAX(d.SEQUENCE_NUMBER) 
		FROM dbo.TB_R_LOG_D d WHERE process_id = @PID;

INSERT dbo.TB_R_LOG_D (process_id, SEQUENCE_NUMBER, MESSAGE_ID, MESSAGE_TYPE, LOCATION, [MESSAGE], CREATED_DATE, CREATED_BY) 
VALUES (@PID, @@lastSeq + 1, @MSG_ID, @MSG_TYPE, @LOCATION, @MSG_TXT, GETDATE(), @USER_ID);

UPDATE dbo.TB_R_LOG_H 
SET 
	FUNCTION_ID = @FUNCTION_ID,
	PROCESS_STATUS = @PROCESS_STS,
	END_DATE = GETDATE()
WHERE PROCESS_ID = @PID

SELECT @PID