IF (@ID = 'AS400')
BEGIN
	SELECT
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_AS4DL') AS HOST_NAME,
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_AS4USR') AS USER_NAME,
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_AS4PWD') AS PASSWORD  
END 
ELSE IF (@ID = 'SAP')
BEGIN
	SELECT
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_SAPDL') AS HOST_NAME,
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_SAPUSR') AS USER_NAME,
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_SAPPWD') AS PASSWORD 
END 
ELSE IF (@ID = 'SUCCESS')
BEGIN
	SELECT
		(SELECT VALUE FROM TB_M_SYSTEM WHERE SYS_CAT='SAP_SYNC' AND SYS_SUB_CAT='OUTPUT_FOLDER' AND SYS_CD = @PARAM) AS HOST_NAME,
		(SELECT VALUE FROM TB_M_SYSTEM WHERE SYS_CAT='SAP_SYNC' AND SYS_SUB_CAT='OUTPUT_FOLDER' AND SYS_CD = 'SUCCESS') AS HOST_NAME_SUCCESS,
		(SELECT VALUE FROM TB_M_SYSTEM WHERE SYS_CAT='SAP_SYNC' AND SYS_SUB_CAT='FTP_ACC' AND SYS_CD = 'FTP_USERNAME') AS USER_NAME,
		(SELECT VALUE FROM TB_M_SYSTEM WHERE SYS_CAT='SAP_SYNC' AND SYS_SUB_CAT='FTP_ACC' AND SYS_CD = 'FTP_PWD') AS PASSWORD
END 
ELSE IF (@ID = 'FAILED')
BEGIN
	SELECT
		(SELECT VALUE FROM TB_M_SYSTEM WHERE SYS_CAT='SAP_SYNC' AND SYS_SUB_CAT='OUTPUT_FOLDER' AND SYS_CD = @PARAM) AS HOST_NAME,
		(SELECT VALUE FROM TB_M_SYSTEM WHERE SYS_CAT='SAP_SYNC' AND SYS_SUB_CAT='OUTPUT_FOLDER' AND SYS_CD = 'FAILED') AS HOST_NAME_FAILED,
		(SELECT VALUE FROM TB_M_SYSTEM WHERE SYS_CAT='SAP_SYNC' AND SYS_SUB_CAT='FTP_ACC' AND SYS_CD = 'FTP_USERNAME') AS USER_NAME,
		(SELECT VALUE FROM TB_M_SYSTEM WHERE SYS_CAT='SAP_SYNC' AND SYS_SUB_CAT='FTP_ACC' AND SYS_CD = 'FTP_PWD') AS PASSWORD
END 