IF (@ID = 'SAP')
BEGIN
	SELECT
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_SAPURL') AS HOST_NAME,
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_SAPUSR') AS USER_NAME,
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_SAPPWD') AS PASSWORD 
END 
ELSE IF (@ID = 'AS400')
BEGIN
	SELECT
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_AS4URL') AS HOST_NAME,
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_AS4USR') AS USER_NAME,
		(SELECT V_NAME_VALUE FROM MS_SYSTEM WHERE V_SYSTEM_CD = 'FTP_AS4PWD') AS PASSWORD 
END