--DECLARE @@dockServicePartTable AS TABLE (DOCK VARCHAR(2))
DECLARE @@TP_SUPPLIER_CODE VARCHAR(50), 
		@@TYPE_CODE int, 
		@@SYS_SOURCE VARCHAR(20), 
		@@MAT_DOC_DESC VARCHAR(200), 
		@@PROD_PURPOSE_CD VARCHAR(5), 
		@@SOURCE_TYPE_TP VARCHAR(1),
		@@dockServicePart VARCHAR(20) = '',
		@@prodPurposeServicePart VARCHAR(20) = '',
		@@URI_UOM VARCHAR(5),
		@@FLTR_DATETIME_VALUE AS VARCHAR(50) ,
		@@FLTR_LOGICAL_VALUE AS VARCHAR(50) ,
		@@FLTR_FLAG_VALUE AS VARCHAR(50),
		@@IS_VALID_FILTER VARCHAR(1),
		@@clientId VARCHAR(3)


set @@TYPE_CODE =42001

-- set doc val
SELECT  @@dockServicePart = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'DOCK_SERVICE_PART'
SELECT  @@TP_SUPPLIER_CODE = dbo.GET_VALUE_FROM_M_SYSTEM(@@TYPE_CODE,'TP_SPLR_CODE')+ '%'
SELECT  @@SYS_SOURCE = dbo.GET_VALUE_FROM_M_SYSTEM(@@TYPE_CODE,'SYSTEM_SOURCE_GR')
SELECT  @@PROD_PURPOSE_CD = dbo.GET_VALUE_FROM_M_SYSTEM(@@TYPE_CODE,'PROD_PURPOSE_CD_GR')
SELECT  @@prodPurposeServicePart = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'PROD_PURPOSE_GR_SERVICE_PART'
SELECT  @@SOURCE_TYPE_TP = dbo.GET_VALUE_FROM_M_SYSTEM(@@TYPE_CODE,'SOURCE_TYPE_TP')
SELECT  @@MAT_DOC_DESC = dbo.GET_VALUE_FROM_M_SYSTEM(@@TYPE_CODE,'MAT_DOC_DESC')
SELECT  @@URI_UOM = dbo.GET_VALUE_FROM_M_SYSTEM(@@TYPE_CODE,'ORI_UNIT_MEASU_CD_GR')
SELECT  @@FLTR_DATETIME_VALUE = LTRIM(RTRIM(dbo.GET_VALUE_FROM_M_SYSTEM(@@TYPE_CODE,'POST_TIME_FLTR')))
SELECT  @@FLTR_LOGICAL_VALUE = LTRIM(RTRIM(dbo.GET_VALUE_FROM_M_SYSTEM(@@TYPE_CODE,'POST_LGCL_FLTR')))
SELECT  @@FLTR_FLAG_VALUE = LTRIM(RTRIM(dbo.GET_VALUE_FROM_M_SYSTEM(@@TYPE_CODE,'POST_FLG_FLTR')))
SELECT  @@clientId = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_CD = 'TP_CLIENT_ID'


SELECT @@dockServicePart AS DOCK_SERVICE_PART
	  ,@@TP_SUPPLIER_CODE AS TP_SPLR_CODE
	  ,@@SYS_SOURCE AS SYSTEM_SOURCE_GR
	  ,@@PROD_PURPOSE_CD AS PROD_PURPOSE_CD_GR
	  ,@@prodPurposeServicePart AS PROD_PURPOSE_GR_SERVICE_PART
	  ,@@SOURCE_TYPE_TP AS SOURCE_TYPE_TP
	  ,@@MAT_DOC_DESC AS MAT_DOC_DESC
	  ,@@URI_UOM AS ORI_UNIT_MEASU_CD_GR
	  ,@@FLTR_DATETIME_VALUE AS POST_TIME_FLTR
	  ,@@FLTR_LOGICAL_VALUE AS POST_LGCL_FLTR
	  ,@@FLTR_FLAG_VALUE AS POST_FLG_FLTR
	  ,@@TYPE_CODE AS TYPE_CODE
	  ,@@clientId AS clientId