DECLARE @@COMPANY_CD VARCHAR(4);

SELECT 
	PROD_PLAN_ID_CD,USER_CD,CFC,SS_NO,BASIC,
	PART_NO,COLOR_SUFFIX,SOURCE_CD,F_DUMMY,
	ID_LINE,F_DUMMY,DEST_CD,F_DUMMY,REP_PART_FLAG,OFF_OPT_CD,
	PROD_PLANT_TYPE,CONCAT(F_COMPANY_CD,F_STATUS_CD,F_LINE_CD,F_EXPORT_CD) [FREE_AREA],
	@@COMPANY_CD, F_EXPORT_CD, F_STATUS_CD, F_LINE_CD, convert(varchar, START_DT, 112) [START_DT],
	EFF_RANGE_DAY_QTY,DAY_QTY_01,DAY_QTY_02,DAY_QTY_03,DAY_QTY_04,DAY_QTY_05,DAY_QTY_06,
	DAY_QTY_07,DAY_QTY_08,DAY_QTY_09,DAY_QTY_10,DAY_QTY_11,DAY_QTY_12,DAY_QTY_13,DAY_QTY_14,
	DAY_QTY_15,DAY_QTY_16,DAY_QTY_17,DAY_QTY_18,DAY_QTY_19,DAY_QTY_20,DAY_QTY_21,DAY_QTY_22,
	DAY_QTY_23,DAY_QTY_24,DAY_QTY_25,DAY_QTY_26,DAY_QTY_27,DAY_QTY_28,DAY_QTY_29,DAY_QTY_30,
	DAY_QTY_31,DAY_QTY_SIGN_01,DAY_QTY_SIGN_02,DAY_QTY_SIGN_03,DAY_QTY_SIGN_04,DAY_QTY_SIGN_05,
	DAY_QTY_SIGN_06,DAY_QTY_SIGN_07,DAY_QTY_SIGN_08,DAY_QTY_SIGN_09,DAY_QTY_SIGN_10,DAY_QTY_SIGN_11,
	DAY_QTY_SIGN_12,DAY_QTY_SIGN_13,DAY_QTY_SIGN_14,DAY_QTY_SIGN_15,DAY_QTY_SIGN_16,DAY_QTY_SIGN_17,
	DAY_QTY_SIGN_18,DAY_QTY_SIGN_19,DAY_QTY_SIGN_20,DAY_QTY_SIGN_21,DAY_QTY_SIGN_22,DAY_QTY_SIGN_23,
	DAY_QTY_SIGN_24,DAY_QTY_SIGN_25,DAY_QTY_SIGN_26,DAY_QTY_SIGN_27,DAY_QTY_SIGN_28,DAY_QTY_SIGN_29,
	DAY_QTY_SIGN_30,DAY_QTY_SIGN_31,CYCLE_FLAG,START_DT_TOTAL_QTY,EFF_RANGE_TOTAL_QTY,TOTAL_QTY_SIGN_01,
	TOTAL_QTY_01,F_DUMMY
	FROM dbo.TB_R_K_NQC_INTERFACE trkni
UNION all
SELECT PROD_PLAN_ID_CD,USER_CD,CFC,SS_NO,BASIC,
	PART_NO,COLOR_SUFFIX,SOURCE_CD,F_DUMMY,
	ID_LINE,F_DUMMY,DEST_CD,F_DUMMY,REP_PART_FLAG,OFF_OPT_CD,
	PROD_PLANT_TYPE,CONCAT(F_COMPANY_CD,F_STATUS_CD,F_LINE_CD,F_EXPORT_CD) [FREE_AREA],
	@@COMPANY_CD, F_EXPORT_CD, F_STATUS_CD, F_LINE_CD, convert(varchar, START_DT, 112) [START_DT],
	EFF_RANGE_DAY_QTY,DAY_QTY_01,DAY_QTY_02,DAY_QTY_03,DAY_QTY_04,DAY_QTY_05,DAY_QTY_06,
	DAY_QTY_07,DAY_QTY_08,DAY_QTY_09,DAY_QTY_10,DAY_QTY_11,DAY_QTY_12,DAY_QTY_13,DAY_QTY_14,
	DAY_QTY_15,DAY_QTY_16,DAY_QTY_17,DAY_QTY_18,DAY_QTY_19,DAY_QTY_20,DAY_QTY_21,DAY_QTY_22,
	DAY_QTY_23,DAY_QTY_24,DAY_QTY_25,DAY_QTY_26,DAY_QTY_27,DAY_QTY_28,DAY_QTY_29,DAY_QTY_30,
	DAY_QTY_31,DAY_QTY_SIGN_01,DAY_QTY_SIGN_02,DAY_QTY_SIGN_03,DAY_QTY_SIGN_04,DAY_QTY_SIGN_05,
	DAY_QTY_SIGN_06,DAY_QTY_SIGN_07,DAY_QTY_SIGN_08,DAY_QTY_SIGN_09,DAY_QTY_SIGN_10,DAY_QTY_SIGN_11,
	DAY_QTY_SIGN_12,DAY_QTY_SIGN_13,DAY_QTY_SIGN_14,DAY_QTY_SIGN_15,DAY_QTY_SIGN_16,DAY_QTY_SIGN_17,
	DAY_QTY_SIGN_18,DAY_QTY_SIGN_19,DAY_QTY_SIGN_20,DAY_QTY_SIGN_21,DAY_QTY_SIGN_22,DAY_QTY_SIGN_23,
	DAY_QTY_SIGN_24,DAY_QTY_SIGN_25,DAY_QTY_SIGN_26,DAY_QTY_SIGN_27,DAY_QTY_SIGN_28,DAY_QTY_SIGN_29,
	DAY_QTY_SIGN_30,DAY_QTY_SIGN_31,CYCLE_FLAG,START_DT_TOTAL_QTY,EFF_RANGE_TOTAL_QTY,TOTAL_QTY_SIGN_01,
	TOTAL_QTY_01,F_DUMMY
FROM dbo.TB_R_M_NQC_INTERFACE trkni 

