IF(@param = 'invalid')
BEGIN
	UPDATE TB_T_TRANSFER_POSTING_TO_ICS
	SET DN_COMPLETE_FLAG = 'N'
	WHERE PROCESS_KEY = @PROCESS_KEY
END
ELSE
BEGIN
	UPDATE TB_T_TRANSFER_POSTING_TO_ICS
	SET DN_COMPLETE_FLAG = 'Y'
	WHERE PROCESS_KEY = @PROCESS_KEY
END