SELECT * FROM(

SELECT 
	ROW_NUMBER() OVER (ORDER BY CREATED_DT desc) as r, 
	DEST_CD,
	CFC, 
	SUBSTRING(PART_NO,0,6) AS PART_NO_ONE, 
	SUBSTRING(PART_NO,6,5) AS PART_NO_TWO, 
	SUBSTRING(PART_NO,11,12) AS PART_NO_THREE, 
	COMPANY_CD,
	PROCESS_CD,
	STATUS_CD,
	PART_NAME,
	PART_NO,
	CAST(LOT_SIZE AS VARCHAR) AS LOT_SIZE, 
	SEL_MATCH_RATIO, 
	CONVERT(VARCHAR(MAX), TC_FROM, 112) TC_FROM,
	CONVERT(VARCHAR(MAX), TC_TO, 112) TC_TO,	
	CREATED_BY, 
	CREATED_DT
FROM TB_M_DLV_PACK_PART
WHERE 1=1

  AND ((@DEST_CD is null OR @DEST_CD = '') OR (DEST_CD = @DEST_CD))
  AND ((@CFC is null OR @CFC = '') OR (CFC  = @CFC))
	AND ((@PART_NO is null OR @PART_NO = '') OR (PART_NO like '%' +@PART_NO+'%' ))
	AND ((@PART_NO_ONE is null OR @PART_NO_ONE = '') OR (PART_NO like '%' +@PART_NO_ONE+'%' ))
	AND ((@PART_NO_TWO is null OR @PART_NO_TWO = '') OR (PART_NO like '%' +@PART_NO_TWO+'%' ))
	AND ((@PART_NO_THREE is null OR @PART_NO_THREE = '') OR (PART_NO like '%' +@PART_NO_THREE+'%' ))

)	tb
where 1 = 1 and tb.r between @PageNumber and @PageSize

