CREATE TABLE [dbo].[TB_M_FUNCTION_DEPENDENCY](
	[FUNCTION_MAIN] [varchar](10) NOT NULL,
	[FUNCTION_RELATED] [varchar](10) NOT NULL,
	[TYPE] [int] NULL,
 CONSTRAINT [PK_TB_M_FUNCTION_DEPENDENCY] PRIMARY KEY CLUSTERED 
(
	[FUNCTION_MAIN] ASC,
	[FUNCTION_RELATED] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO