SELECT 
	 MNG.COMPANY_CD, 
	 SPEC.STATUS_CD,
	 SPEC.[VERSION],
	 SPEC.IMPORTER_CD, 
	 SPEC.ORD_TYPE,
	 SPEC.CFC,
	 SPEC.RE_EXPORT_CD,
	 SPEC.AICO_FLAG,
	 SPEC.PART_NO,
	 SPEC.REVISION,
	 SPEC.PACK_MONTH,
	 MN.YYMM,
	 MN.MONTH_ORD_VOL
INTO #Current_Volume
FROM TB_R_ORDER_CONTROL MNG
JOIN TB_R_ORDER_SPEC SPEC ON 
	 MNG.COMPANY_CD   = SPEC.COMPANY_CD AND 
	 MNG.RECEIVE_NO   = SPEC.RECEIVE_NO
JOIN TB_R_ORDER_MONTHLY MN ON 
	 MN.COMPANY_CD    = SPEC.COMPANY_CD AND
	 MN.RECEIVE_NO    = SPEC.RECEIVE_NO AND
	 MN.DETAIL_NO     = SPEC.DETAIL_NO
WHERE
	(
	  (MNG.DIFF_LIST_STAT IS NULL OR MNG.DIFF_LIST_STAT = '') 
	   OR 
	  (MNG.DIFF_LIST_TIME IS NULL OR MNG.DIFF_LIST_TIME = '')
	)
	AND
	(
	  (MNG.CHECK_STAT IS NOT NULL AND LEN(MNG.CHECK_STAT) != 0) 
	   AND 
	  (MNG.CHECK_TIME IS NOT NULL AND LEN(MNG.CHECK_TIME) != 0)
	)
	AND
	MNG.COMPANY_CD   = @company_code AND
	SPEC.IMPORTER_CD = @importer_cd AND
	SPEC.[VERSION]   = @version AND
	SPEC.REVISION    = @revision AND
	SPEC.ORD_TYPE    = @ord_type AND
	SPEC.CFC         = @cfc


SELECT
	SRC.COMPANY_CD, 
	SRC.STATUS_CD,
	SRC.[VERSION],
	SRC.IMPORTER_CD, 
	SRC.ORD_TYPE,
	SRC.CFC,
	SRC.RE_EXPORT_CD,
	SRC.AICO_FLAG,
	SRC.PART_NO,
	SRC.REVISION,
	SRC.PACK_MONTH,
	SRC.YYMM,
	SRC.MONTH_ORD_VOL CURR_VOL,
	COALESCE(DEST.PREV_VOL, 0) PREV_VOL
INTO #Previous_Volume
FROM #Current_Volume SRC
LEFT JOIN (
	SELECT
		Curr.COMPANY_CD, 
		Curr.STATUS_CD,
		Curr.[VERSION],
		Curr.IMPORTER_CD, 
		Curr.ORD_TYPE,
		Curr.CFC,
		Curr.RE_EXPORT_CD,
		Curr.AICO_FLAG,
		Curr.PART_NO,
		Curr.REVISION,
		Curr.PACK_MONTH,
		Curr.YYMM,
		Curr.MONTH_ORD_VOL CURR_VOL,
		WRK.MONTH_ORD_VOL PREV_VOL
	FROM TB_R_ORDER_WORK WRK
	JOIN #Current_Volume Curr ON
		Curr.COMPANY_CD = WRK.COMPANY_CD AND
		Curr.STATUS_CD = WRK.STATUS_CD AND
		Curr.IMPORTER_CD = WRK.IMPORTER_CD AND
		Curr.ORD_TYPE = WRK.ORD_TYPE AND
		Curr.CFC = WRK.CFC AND
		Curr.RE_EXPORT_CD = WRK.RE_EXPORT_CD AND
		Curr.AICO_FLAG = WRK.AICO_FLAG AND
		Curr.PART_NO = WRK.PART_NO AND
		Curr.YYMM = WRK.YYMM
	WHERE WRK.YYMM BETWEEN Curr.PACK_MONTH AND SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 3, CAST(Curr.PACK_MONTH + '01' AS DATE)), 112), 1, 6)
) DEST ON
	SRC.COMPANY_CD   = DEST.COMPANY_CD AND
	SRC.STATUS_CD    = DEST.STATUS_CD AND
	SRC.IMPORTER_CD  = DEST.IMPORTER_CD AND
	SRC.ORD_TYPE     = DEST.ORD_TYPE AND
	SRC.CFC          = DEST.CFC AND
	SRC.RE_EXPORT_CD = DEST.RE_EXPORT_CD AND
	SRC.AICO_FLAG    = DEST.AICO_FLAG AND
	SRC.PART_NO      = DEST.PART_NO AND
	SRC.YYMM         = DEST.YYMM
ORDER BY SRC.PART_NO


SELECT 
	Vol.IMPORTER_CD, 
	Vol.VERSION, 
	Vol.REVISION,
	Vol.ORD_TYPE, 
	Vol.CFC,
	Vol.PACK_MONTH,
	Vol.PART_NO,
	Vol.YYMM,
	CAST(Vol.PREV_VOL AS INT) [PREV_VOL],
	CAST(Vol.CURR_VOL AS INT) [CURR_VOL],
	CAST(Vol.CURR_VOL - Vol.PREV_VOL AS INT) [DIFFERENT_VOL]
INTO #OdrVlmDiffList
FROM #Previous_Volume Vol
ORDER BY PART_NO


DECLARE @@cols  AS NVARCHAR(MAX),
		@@query AS NVARCHAR(MAX)

SELECT @@cols =
	STUFF(
		CAST(
			(SELECT ',' + QUOTENAME(NEW_COL)
			 FROM (
 				SELECT 
 				   CASE
 					  WHEN COL = 'PREV_VOL' THEN 'PREV'
 					  WHEN COL = 'CURR_VOL' THEN 'NOW'
 					  WHEN COL = 'DIFFERENT_VOL' THEN 'DIFF'
 				   END + '_N' + IIF(((NTILE(4) OVER(PARTITION BY PART_NO ORDER BY YYMM ASC) - 1)) = 0, '', '_' + CAST((NTILE(4) OVER(PARTITION BY PART_NO ORDER BY YYMM ASC) - 1) AS VARCHAR)) NEW_COL,
				   YYMM
 				FROM   #OdrVlmDiffList
 				UNPIVOT(
 					VALUE
 					FOR COL IN ([PREV_VOL], [CURR_VOL], [DIFFERENT_VOL])
 				) UP
			 ) A
			 GROUP BY NEW_COL, YYMM
			 ORDER BY YYMM ASC, NEW_COL DESC
			 FOR XML PATH(''), TYPE)
		AS NVARCHAR(MAX)),
	1, 1, '')

SET @@query = '
	SELECT *
	FROM (
		SELECT IMPORTER_CD DESTINATION_CD,
			   CASE VERSION 
				WHEN ''T'' THEN ''TENTATIVE''
				WHEN ''F'' THEN ''FIRM''
				WHEN ''K'' THEN ''KEIHEN''
			   END [VERSION],
			   REVISION REVISION_NO, 
			   ORD_TYPE ORDER_TYPE,
			   PART_NO,
			   CFC CAR_FAMILY_CODE,
			   PACK_MONTH NMONTH,
			   SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 1, PACK_MONTH + ''01''), 112), 1, 6) [NMONTH_1],
			   SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 2, PACK_MONTH + ''01''), 112), 1, 6) [NMONTH_2],
			   SUBSTRING(CONVERT(VARCHAR, DATEADD(MONTH, 3, PACK_MONTH + ''01''), 112), 1, 6) [NMONTH_3],
			   CASE
				  WHEN COL = ''PREV_VOL'' THEN ''Prev''
				  WHEN COL = ''CURR_VOL'' THEN ''Now''
				  WHEN COL = ''DIFFERENT_VOL'' THEN ''Diff''
			   END + ''_N'' + IIF(((NTILE(4) OVER(PARTITION BY PART_NO ORDER BY YYMM ASC) - 1)) = 0, '''', ''_'' + CAST((NTILE(4) OVER(PARTITION BY PART_NO ORDER BY YYMM ASC) - 1) AS VARCHAR)) NEW_COL,
			   VALUE
		FROM   #OdrVlmDiffList
		UNPIVOT(
			VALUE
			FOR COL IN ([PREV_VOL], [CURR_VOL], [DIFFERENT_VOL])
		) UP
	) SRC
	PIVOT(
		SUM(VALUE)
		FOR NEW_COL IN ('+ @@cols +')
	) PVT
	ORDER BY PART_NO	
'; 
EXECUTE(@@query)