SELECT 
	 MNG.COMPANY_CD,
	 SPEC.IMPORTER_CD DESTINATION_CD, 
	 CASE SPEC.[VERSION] 
		WHEN 'T' THEN 'TENTATIVE'
		WHEN 'F' THEN 'FIRM'
		WHEN 'K' THEN 'KEIHEN'
	 END  [VERSION_NAME],
	 SPEC.[VERSION],
	 SPEC.REVISION REVISION_NO,
	 SPEC.ORD_TYPE ORDER_TYPE,
	 SPEC.CFC CAR_FAMILY_CODE
FROM TB_R_ORDER_CONTROL MNG
JOIN TB_R_ORDER_SPEC SPEC ON 
	 MNG.COMPANY_CD = SPEC.COMPANY_CD AND 
	 MNG.RECEIVE_NO = SPEC.RECEIVE_NO
JOIN TB_R_ORDER_MONTHLY MN ON 
	 MN.COMPANY_CD = SPEC.COMPANY_CD AND
	 MN.RECEIVE_NO = SPEC.RECEIVE_NO AND
	 MN.DETAIL_NO = SPEC.DETAIL_NO
JOIN TB_R_ORDER_WORK WRK ON
	 SPEC.COMPANY_CD = WRK.COMPANY_CD AND
	 SPEC.STATUS_CD = WRK.STATUS_CD AND
	 SPEC.IMPORTER_CD = WRK.IMPORTER_CD AND
	 SPEC.ORD_TYPE = WRK.ORD_TYPE AND
	 SPEC.CFC = WRK.CFC AND
	 SPEC.RE_EXPORT_CD = WRK.RE_EXPORT_CD AND
	 SPEC.AICO_FLAG = WRK.AICO_FLAG AND
	 SPEC.PART_NO = WRK.PART_NO AND
	 MN.YYMM = WRK.YYMM
WHERE
	(
	  (MNG.DIFF_LIST_STAT IS NULL OR MNG.DIFF_LIST_STAT = '') 
	   OR 
	  (MNG.DIFF_LIST_TIME IS NULL OR MNG.DIFF_LIST_TIME = '')
	)
	AND
	(
	  (MNG.CHECK_STAT IS NOT NULL AND LEN(MNG.CHECK_STAT) != 0) 
	   AND 
	  (MNG.CHECK_TIME IS NOT NULL AND LEN(MNG.CHECK_TIME) != 0)
	)
	AND MNG.COMPANY_CD = @company_cd
GROUP BY
	MNG.COMPANY_CD,
	SPEC.IMPORTER_CD, 
	SPEC.[VERSION],
	SPEC.REVISION,
	SPEC.ORD_TYPE,
	SPEC.CFC