UPDATE TB_R_ORDER_CONTROL
SET DIFF_LIST_STAT = 'OK', 
	DIFF_LIST_TIME = CONVERT(VARCHAR, GETDATE(), 112) + REPLACE(CONVERT(VARCHAR, GETDATE(),108),':','')
WHERE
	(
	  (DIFF_LIST_STAT IS NULL OR DIFF_LIST_STAT = '') 
	   OR 
	  (DIFF_LIST_TIME IS NULL OR DIFF_LIST_TIME = '')
	)
	AND
	(
	  (CHECK_STAT IS NOT NULL AND LEN(CHECK_STAT) != 0) 
	   AND 
	  (CHECK_TIME IS NOT NULL AND LEN(CHECK_TIME) != 0)
	) 
	AND COMPANY_CD = @company_code