SELECT 
	ROW_NUMBER() OVER (ORDER BY CREATED_DT desc) as r, 
		IMPORTER_CD,
		EXPORTER_CD,ORD_TYPE,PACK_MONTH, CFC,
		RECEIVE_NO,
		STATUS_CD,
		COMPANY_CD
	 ,
	 --CONVERT(VARCHAR, CONCAT((SUBSTRING( K_PACK_CREATE_TIME,0,5)),'-',(SUBSTRING(K_PACK_CREATE_TIME,5,2)),'-',(SUBSTRING(K_PACK_CREATE_TIME,5,2))),112) as [START_DATE]
	FORMAT (getdate(), 'MM-dd-yy') as [START_DATE]
	
FROM TB_R_ORDER_CONTROL
	WHERE 1 =1
	 AND (PACK_MONTH = CONVERT(char(6), getdate(), 112) OR PACK_MONTH = CONVERT(char(6), DATEADD(MONTH,1,GETDATE()), 112))
	 AND DISABLE_FLAG = '0' 
	 AND (
		(FIRM_REV <> '0' AND KEIHEN_REV = '0')
		OR
		(FIRM_REV <> '0' AND KEIHEN_REV <> '0')
	 )
	 AND COMPANY_CD = @COMPANY_CD
	 AND (
		   (CHECK_STAT = 'OK' AND (DAY_BY_DAY_STAT = '------' OR DAY_BY_DAY_STAT = '' OR DAY_BY_DAY_STAT IS NULL OR LEN(DAY_BY_DAY_STAT) = 0)) 
		OR (CHECK_STAT = 'OK' AND DAY_BY_DAY_STAT = 'ERR')
		OR (CHECK_STAT = 'OK' AND DAY_BY_DAY_STAT LIKE '%(W)')
		OR (CHECK_STAT LIKE '%(W)' AND (DAY_BY_DAY_STAT = '------' OR DAY_BY_DAY_STAT = '' OR DAY_BY_DAY_STAT IS NULL OR LEN(DAY_BY_DAY_STAT) = 0))
		OR (CHECK_STAT LIKE '%(W)' AND DAY_BY_DAY_STAT = 'ERR')
		OR (CHECK_STAT LIKE '%(W)' AND DAY_BY_DAY_STAT LIKE '%(W)')
	 )
ORDER BY CHECK_TIME DESC
	 